# Generated by Django 3.0.3 on 2020-03-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla')),
                ('data_inicio', models.DateField(blank=True, max_length=20, null=True, verbose_name='data de inicio')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('valor', models.FloatField(blank=True, max_length=20, null=True, verbose_name='valor')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.Evento', verbose_name='Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisca',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_ingresso.Pessoa')),
                ('cpf', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF')),
            ],
            bases=('app_ingresso.pessoa',),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.Evento')),
                ('ingressos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.Ingresso')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='realizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.Pessoa'),
        ),
    ]
